# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79429adf627c2a567e439ff5628f5b93b907cce1edd824dc8fa633a62443dd7964a68e0d3d084ac14634ddab0d54680a5790ebe1aa2d8fbeb166b62f92e78108

test:
  secret_key_base: 35a2cdb508d01cb3485fd8c9f1b99c4c4b48ac5822782233a238f86e52a5cc95096d11920b742139e94084e03aca4e7acf5129f352ec77aa44b5373a5aa29d4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
